// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW9qtotVZUBce3aP-l2HBS1RBbqGfib88',
    appId: '1:293641434259:web:ab33690896835188e24966',
    messagingSenderId: '293641434259',
    projectId: 'news-application-9e256',
    authDomain: 'news-application-9e256.firebaseapp.com',
    storageBucket: 'news-application-9e256.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7vnPL4rJpRYK0Ku1A_NPw3Rd7SiWPoE',
    appId: '1:293641434259:android:6017e089b26b6070e24966',
    messagingSenderId: '293641434259',
    projectId: 'news-application-9e256',
    storageBucket: 'news-application-9e256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC43pe7So4dXmskfbuTjwSE0oEJg6XeCWM',
    appId: '1:293641434259:ios:2765c1fc9896cff5e24966',
    messagingSenderId: '293641434259',
    projectId: 'news-application-9e256',
    storageBucket: 'news-application-9e256.appspot.com',
    iosBundleId: 'com.example.newsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC43pe7So4dXmskfbuTjwSE0oEJg6XeCWM',
    appId: '1:293641434259:ios:c09faa9ce5378d0ee24966',
    messagingSenderId: '293641434259',
    projectId: 'news-application-9e256',
    storageBucket: 'news-application-9e256.appspot.com',
    iosBundleId: 'com.example.newsApplication.RunnerTests',
  );
}
